### ISSUE TITLE
problem with using nav-element

### ISSUE THREAD

**Issue by alisedaghatbaf** [vivekmore/generator-jhipster-nav-element#1]
Hi, 
It seems that the nav-element generator does not work with JHipster v4.6.2. I get the following compilation error when using this generator:
ERROR in [at-loader] ./src/main/webapp/app/about-us/about-us.component.ts:16:29
    TS2339: Property 'setLocations' does not exist on type 'JhiLanguageService'.

**Comment by vivekmore** [comment]
Please provide more details for me to reproduce the issue.
e.g. 
- the node/npm version you are using
- your generator-jhipster-nav-element version
- what options you chose when you created your jhipster project e.g. your .yo-rc.json

**Comment by vivekmore** [comment]
I was able to reproduce this issue.
A fix will be available soon :)
